# Generated by Django 4.1.5 on 2023-01-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_ward_municipality_alter_ward_name_testdisastermodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_name", models.CharField(max_length=255)),
                ("deployed_inventory", models.IntegerField()),
                ("time_of_action", models.DateTimeField(auto_now_add=True)),
                (
                    "disaster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.testdisastermodel",
                    ),
                ),
            ],
        ),
    ]
